name: Unit Converter - uniconv.c

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build uniconv
        run: make test

      - name: upload binary
        uses: actions/upload-artifact@v4
        with:
          name: Run Unit Converter
          path: ./uniconv
