name: Build script for uniconv

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build uniconv
        run: make uniconv

      - name: upload binary
        uses: actions/upload-artifact@v4
        with:
          name: Uniconv
          path: ./uniconv
