name: Build Script For conversion.c

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build conversion
        run: make conversion

      - name: upload binary
        uses: actions/upload-artifact@v4
        with:
          name: Clean Data
          path: ./conversion
