name: CI - Test Uniconv Utility

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        run: make ctest; bash test_script >test_results.txt

      - name: Run gcov
        run: gcov ctest-uniconv.c ctest-message.c ctest-read_input.c ctest-calculate_conversion.c ctest-print_output.c ctest-error.c
        
      - name: Upload Test Results
        if: ${{ always() }}

        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: |
            ./test_results.txt
            ./*.c.gcov
